# Generated by Django 4.2.23 on 2025-07-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='condition',
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(default='not provided', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
